site_name: HowToLearn
repo_url: https://github.com/GloomyBee/HowToLearn
repo_name: GitHub
theme:
  name: material
  palette:
    primary: indigo
    scheme: default
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - toc.integrate
    - search.suggest
nav:
  - 首页: index.md
  - Tags: tags.md
plugins:
  - search
  - tags
  - git-revision-date-localized:
      fallback_to_build_date: true
      type: date
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
