site_name: HowToLearn
theme:
  name: material
  palette:
    primary: indigo
    scheme: default  # 支持暗黑/明亮模式切换
  features:
    - content.code.copy  # 代码块复制按钮
    - navigation.tabs    # 顶部导航
    - search.suggest     # 搜索建议
#nav:
#  - 首页: index.md
#  - 文件夹:
#      - 子文件夹: test1/
#  - 文件夹2:
#      - 子文件夹: test2/
plugins:
  - search
  - tags
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:  # 代码高亮
      anchor_linenums: true
  - pymdownx.superfences  # 增强代码块
  - attr_list  # 支持图片大小等属性
  - pymdownx.emoji  # 支持 emoji
  
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
